name: pvtend_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - xarray
  - pandas
  - netcdf4
  - tqdm
  - matplotlib
  - cartopy
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - ipykernel
